### ISSUE TITLE
[Question] relationship with other tables in AlbumTableGateway ?

### ISSUE THREAD

**Issue by greermurray** [lowtower/zend-expressive2-tutorial#24]
if my album is related to other tables in my database, how do I implement it in AlbumTableGateway?
example, if I have another table called categories ...

**Comment by lowtower** [comment]
Hello @greermurray,

this is not really an issue, isn't it?
Rather a question.
The best place for asking questions related to zend-expressive or zend-framework is the [the zend forum](https://discourse.zendframework.com).

Nevertheless: create a method that fulfills You needs, e.g. that selects from the second table using joins. Have a look at the `from()` method at the [zend-db manual](https://docs.zendframework.com/zend-db/sql/#select).

Cheers,
LT.
